name: Python application

on:
  push:
    branches:
      - main  # Kodun main dalına gönderildiğinde çalışacak
  pull_request:
    branches:
      - main  # Pull request açıldığında çalışacak

jobs:
  test:
    runs-on: ubuntu-latest  # Testler Ubuntu üzerinde çalışacak

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # GitHub reposunu indirme

    - name: Set up Python
      uses: actions/setup-python@v4  # Python kurulumunu yapar
      with:
        python-version: '3.10'  # Hangi Python sürümünü kullanacağı

    - name: Install pip (skip requirements)
      run: |
        python -m pip install --upgrade pip  # Pip'i güncelle

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"  # Testleri çalıştırır
